spring.application.name=cloudops

aws.region=ca-central-1
aws.dynamodb.table-name=CloudOpsIncidents

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.ca-central-1.amazonaws.com/ca-central-1_UkaFAfWNL
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.ca-central-1.amazonaws.com/ca-central-1_UkaFAfWNL/.well-known/jwks.json